/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dormirelhilo;

/*
    Cuando se ejecuta una aplicación de ventana basada en un formulario
    JFrame, la máquina virtual de Java crea tres hilos por defecto:

    1. El principal, donde corre el método Main() que inicia la aplicación
    2. El conocido como GC (recolector de basura), donde corre el código
       que se encarga de optimizar los recursos de memoria.
    3. El conocido como EDT (hilo despachador de eventos) de la AWT
       (paquete abstracto de herramientas de ventana), donde corre el código
       encargado de atender las solicitudes de dibujo del contenido de la ventana,
       y de atender a los eventos de ratón o teclado provocados por el usuario
       (como la ejecución del código programado para cuando el usuario hace
       click en un botón)

    Puesto que el hilo EDT puede llegar a ser el más ocupado de los tres con
    diferencia, debe de ponerse especial cuidado en no sobrecargarlo demasiado.

    En esta aplicación queremos realizar una cuenta de 1 a 20, cuyo avance
    se vaya reflejando en el JPanel que he colocado a modo de marcador.
    La cuenta se pondrá en marcha cuando el usuario haga click en un botón.

    Obviamente, para reflejar ese avance es necesario repintar el JPanel a cada
    nuevo valor (lo que se le solicita al hilo EDT - que es el encargado de ello,
    mediante una llamada al método repaint() del JPanel).

    El primer botón intenta hacerlo sin poner más hilos en juego.
    No lo consigue.
    Y no lo consigue porque precisamente el hilo que recibe las peticiones de
    pintado, es justo el que las está enviando a cada nuevo valor de la cuenta.
    Y claro, se satura.
    Sólo cuando finaliza la cuenta (justo en el 20), puede atender por fin a la
    solicitud de dibujo del marcador.
    
    Por el contrario, el segundo y el tercer botón delega en un hilo auxiliar,
    tanto la cuenta como las peticiones de repintado del marcador.
    Además este hilo auxiliar, en el caso del Botón 3 se duerme una décima de 
    segundo por cuenta, para que EDT tenga una buena ocasión de atender la
    petición de dibujo que le acaba de enviar.
    El resultado es el esperado por fin.
*/

import javax.swing.JFrame;

/**
 *
 * @author kevin
 */
public class JFrameVentana extends JFrame {
    
    //Marcador del formulario
    JPanelMarcador marcador;

    /**
     * Creates new form JFrameVentana
     */
    
    //Constructor
    public JFrameVentana() {
        
        initComponents();
        
        /*
            Asigna un nuevo marcador y lo posiciona en el formulario a
            5 puntos de los márgenes izquierdo y supeperior
        */
        marcador = new JPanelMarcador();
        marcador.setLocation(5, 5);
        
        //Agrega el marcador al formulario
        this.add(marcador);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Marcador que muestra la cuenta de 1 a 20");
        jLabel1.setMaximumSize(new java.awt.Dimension(220, 16));
        jLabel1.setMinimumSize(new java.awt.Dimension(220, 16));
        jLabel1.setPreferredSize(new java.awt.Dimension(220, 16));

        jButton1.setText("Sin hilos auxiliares");

        jButton2.setText("Con un hilo auxiliar sin dormir");

        jButton3.setText("Con un hilo auxiliar y dormido");

        jButton4.setText("Borrar marcador");
        jButton4.setSelected(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Código que se ejecuta cuando el usuario hace click en el primer botón
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        for (int i = 1; i <= 20; i++) {
            //Incrementa el marcador
            marcador.valor = i;
            //Solicita el repintado del marcador
            marcador.repaint();
        }
    }
    
    //Código que se ejecuta cuando el usuario hace clic en el segundo botón
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        //Crea un hilo pasándole como argumento el marcador.
        Thread thIzquierdo = new HiloAuxiliar(false, marcador);
        //Inicia el hilo
        thIzquierdo.start();
    }
    
    //Código que se ejecuta cuando el usuario hace clic en el tercer botón
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
        //Crea un hilo pasándole como argumento el marcador
        Thread thIzquierdo = new HiloAuxiliar(true, marcador);
        //inicia el hilo
        thIzquierdo.start();
    }
    
    //Código que se ejecuta cuando el usuario hace clic en el botón derecho
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
        marcador.valor = 0;
        //Repinta el marcador para borrarlo (si tuviera algo)
        marcador.repaint();
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameVentana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
