/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dormirelhilo;

import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import javax.swing.JPanel;
import java.awt.FontMetrics;

/**
 *
 * @author kevin
 */
public class JPanelMarcador extends JPanel {
    
    //valor que mostrará el panel
    public int valor;

    /**
     * Creates new form JPanelMarcador
     */
    
    //Constructor
    public JPanelMarcador() {
        //valor por defecto
        valor = 0;
        //dimensiona el JPanel
        this.setSize(250, 50);
        //Establece la fuente del texto dibujando
        this.setFont(new Font("Tahoma", 0, 48));
        
    }
    
    @Override
    public void paintComponent(Graphics g) {
        /*
            sombrea el método paintComponent(g) que pinta el JPanel,
            para que lo haga según el valor actual
        */
        super.paintComponent(g);
        //Anchura del panel
        int anchuraPanel = this.getWidth();
        //Convierto el entero en una cadena de texto
        String strValor = String.valueOf(valor);
        /*
            Obtengo el contexto métrico de la fuente con la que
            escribiremos la cadena
        */
        FontMetrics fontMetrics = g.getFontMetrics();
        //Mide la anchura que ocupará la cadena de texto con la fuente elegida
        int anchuraValor = fontMetrics.stringWidth(strValor);
        
        g.setColor(Color.black);
        g.fillRect(0, 0, anchuraPanel, this.getHeight());
        
        /*
            Dibuja la cadena: A 5 puntos de distancia entre la base de
            la línea y el borde inferior, y alineada a la derecha.
        */
        
        if (valor > 0 ) {
            g.setColor(Color.yellow);
            g.drawString(strValor, anchuraPanel - anchuraValor, 
                    fontMetrics.getAscent() - 5);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
